name: Latest blog post workflow

on:
  schedule:
    - cron: '0 8 * * *'
      timezone: 'America/Chicago'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://www.kylereddoch.me/feed.xml"
